* Include-lokale Variablen
* Wird gesetzt in: selkz_input
*  und benutzt in: ucomm_zuru
DATA: li_staro LIKE sy-staro.

*  INCLUDE FM06BF02_UCOMM_AAKT .  " UCOMM_AAKT
INCLUDE zfm06bf02_ucomm_aakt .  " UCOMM_AAKT

*  INCLUDE FM06BF02_UCOMM_AEND .  " UCOMM_AEND
INCLUDE zfm06bf02_ucomm_aend .  " UCOMM_AEND

*  INCLUDE FM06BF02_UCOMM_ANFL .  " UCOMM_ANFL
INCLUDE zfm06bf02_ucomm_anfl .  " UCOMM_ANFL

*  INCLUDE FM06BF02_UCOMM_ANFR .  " UCOMM_ANFR
INCLUDE zfm06bf02_ucomm_anfr .  " UCOMM_ANFR

*  INCLUDE FM06BF02_UCOMM_AUSW .  " UCOMM_AUSW
INCLUDE zfm06bf02_ucomm_ausw .  " UCOMM_AUSW

*INCLUDE FM06BF02_UCOMM_BEST .  " UCOMM_BEST
INCLUDE zfm06bf02_ucomm_best .  " UCOMM_BEST

*  INCLUDE FM06BF02_UCOMM_BUFR .  " UCOMM_BUFR
INCLUDE zfm06bf02_ucomm_bufr .  " UCOMM_BUFR

*  INCLUDE FM06BF02_UCOMM_DETA .  " UCOMM_DETA
INCLUDE zfm06bf02_ucomm_deta .  " UCOMM_DETA

*  INCLUDE FM06BF02_UCOMM_ENDE .  " UCOMM_ENDE
INCLUDE zfm06bf02_ucomm_ende .  " UCOMM_ENDE

*  INCLUDE FM06BF02_UCOMM_FRST .  " UCOMM_FRST
INCLUDE zfm06bf02_ucomm_frst .  " UCOMM_FRST

*  INCLUDE FM06BF02_UCOMM_HICK .  " UCOMM_HICK
INCLUDE zfm06bf02_ucomm_hick .  " UCOMM_HICK

*  INCLUDE FM06BF02_UCOMM_KICK .  " UCOMM_KICK
INCLUDE zfm06bf02_ucomm_kick .  " UCOMM_KICK

*  INCLUDE FM06BF02_UCOMM_MAKT .  " UCOMM_MAKT
INCLUDE zfm06bf02_ucomm_makt .  " UCOMM_MAKT

*  INCLUDE FM06BF02_UCOMM_MALL .  " UCOMM_MALL
INCLUDE zfm06bf02_ucomm_mall .  " UCOMM_MALL

*  INCLUDE FM06BF02_UCOMM_MARK .  " UCOMM_MARK
INCLUDE zfm06bf02_ucomm_mark .  " UCOMM_MARK

*  INCLUDE FM06BF02_UCOMM_MDEL .  " UCOMM_MDEL
INCLUDE zfm06bf02_ucomm_mdel .  " UCOMM_MDEL

*  INCLUDE FM06BF02_UCOMM_MINT .  " UCOMM_MINT
INCLUDE zfm06bf02_ucomm_mint .  " UCOMM_MINT

*  INCLUDE FM06BF02_UCOMM_MATN .  " UCOMM_MATN
INCLUDE zfm06bf02_ucomm_matn .  " UCOMM_MATN

*  INCLUDE FM06BF02_UCOMM_MMBE .  " UCOMM_MMBE
INCLUDE zfm06bf02_ucomm_mmbe .  " UCOMM_MMBE

*  INCLUDE FM06BF02_UCOMM_MD04 .  " UCOMM_MD04
INCLUDE zfm06bf02_ucomm_md04 .  " UCOMM_MD04

*  INCLUDE FM06BF02_UCOMM_ME54 .  " UCOMM_ME54
INCLUDE zfm06bf02_ucomm_me54 .  " UCOMM_ME54

*  INCLUDE FM06BF02_UCOMM_LINF .  " UCOMM_LINF
INCLUDE zfm06bf02_ucomm_linf .  " UCOMM_LINF

*  INCLUDE FM06BF02_UCOMM_LIBE .  " UCOMM_LIBE
INCLUDE zfm06bf02_ucomm_libe .  " UCOMM_LIBE

*  INCLUDE FM06BF02_UCOMM_LKON .  " UCOMM_LKON
INCLUDE zfm06bf02_ucomm_lkon .  " UCOMM_LKON

*  INCLUDE FM06BF02_UCOMM_LRAC .  " UCOMM_LRAC
INCLUDE zfm06bf02_ucomm_lrac .  " UCOMM_LRAC

*  INCLUDE FM06BF02_UCOMM_LRAM .  " UCOMM_LRAM
INCLUDE zfm06bf02_ucomm_lram .  " UCOMM_LRAM

*INCLUDE FM06BF02_UCOMM_LUAE .  " UCOMM_LUAE
INCLUDE zfm06bf02_ucomm_luae .  " UCOMM_LUAE

*  INCLUDE FM06BF02_UCOMM_ORDB .  " UCOMM_ORDB
INCLUDE zfm06bf02_ucomm_ordb .  " UCOMM_ORDB

*  INCLUDE FM06BF02_UCOMM_ORDM .  " UCOMM_ORDM
INCLUDE zfm06bf02_ucomm_ordm .  " UCOMM_ORDM

*  INCLUDE FM06BF02_UCOMM_SORT .  " UCOMM_SORT
INCLUDE zfm06bf02_ucomm_sort .  " UCOMM_SORT

*  INCLUDE FM06BF02_UCOMM_ZANZ .  " UCOMM_ZANZ
INCLUDE zfm06bf02_ucomm_zanz .  " UCOMM_ZANZ

*  INCLUDE FM06BF02_UCOMM_ZBEA .  " UCOMM_ZBEA
INCLUDE zfm06bf02_ucomm_zbea .  " UCOMM_ZBEA

*  INCLUDE FM06BF02_UCOMM_ZBUP .  " UCOMM_ZBUP
INCLUDE zfm06bf02_ucomm_zbup .  " UCOMM_ZBUP

*  INCLUDE FM06BF02_UCOMM_ZLIS .  " UCOMM_ZLIS
INCLUDE zfm06bf02_ucomm_zlis .  " UCOMM_ZLIS

*  INCLUDE FM06BF02_UCOMM_GLIS .  " UCOMM_GLIS
INCLUDE zfm06bf02_ucomm_glis .  " UCOMM_GLIS

*  INCLUDE FM06BF02_UCOMM_GBUP .  " UCOMM_GBUP
INCLUDE zfm06bf02_ucomm_gbup .  " UCOMM_GBUP

*  INCLUDE FM06BF02_UCOMM_ZRES .  " UCOMM_ZRES
INCLUDE zfm06bf02_ucomm_zres .  " UCOMM_ZRES

*  INCLUDE FM06BF02_UCOMM_ZURU .  " UCOMM_ZURU
INCLUDE zfm06bf02_ucomm_zuru .  " UCOMM_ZURU

*  INCLUDE FM06BF02_LISTE_MERKEN .  " LISTE_MERKEN
INCLUDE zfm06bf02_liste_merken .  " LISTE_MERKEN

*  INCLUDE FM06BF02_SELKZ_INPUT .  " SELKZ_INPUT
INCLUDE zfm06bf02_selkz_input .  " SELKZ_INPUT

*  INCLUDE FM06BF02_USER_COMMAND .  " USER_COMMAND
INCLUDE zfm06bf02_user_command .  " USER_COMMAND
