*  INCLUDE FM06BF05_BAN_UPDATE .  " BAN_UPDATE
*
*  INCLUDE FM06BF05_BAN_UPDATE_AENDERN .  " BAN_UPDATE_AENDERN
*
*  INCLUDE FM06BF05_BAT_AUFBAUEN .  " BAT_AUFBAUEN
*
*  INCLUDE FM06BF05_GENERIEREN_ANFRAGE .  " GENERIEREN_ANFRAGE
*
*  INCLUDE FM06BF05_GENERIEREN_BESTELLUNG .  " GENERIEREN_BESTELLUNG
*
*  INCLUDE FM06BF05_GENERIEREN_ERFASSUNGS .  " GENERIEREN_ERFASSUNGSBLATT
*
*  INCLUDE FM06BF05_GENERIEREN_EINTEILUNG .  " GENERIEREN_EINTEILUNG
*
*  INCLUDE FM06BF05_GENERIEREN_UMLAGBESTE .  " GENERIEREN_UMLAGBESTELLUNG
*
*  INCLUDE FM06BF05_ZUG_AENDERN .  " ZUG_AENDERN
*
*  INCLUDE FM06BF05_ZUG_BEARBEITEN .  " ZUG_BEARBEITEN
*
*  INCLUDE FM06BF05_ZUG_CLEAR .  " ZUG_CLEAR
*
*  INCLUDE FM06BF05_ZUG_HIDE .  " ZUG_HIDE
*
*  INCLUDE FM06BF05_ZUG_MODIF_ZEILE .  " ZUG_MODIF_ZEILE
*
*  INCLUDE FM06BF05_ZUG_SUMME .  " ZUG_SUMME
*
*  INCLUDE FM06BF05_ZUG_SUMME_ANFR .  " ZUG_SUMME_ANFR
*
*  INCLUDE FM06BF05_ZUG_SUMME_LIEF .  " ZUG_SUMME_LIEF
*
*  INCLUDE FM06BF05_ZUG_SUMME_OHNE .  " ZUG_SUMME_OHNE
*
*  INCLUDE FM06BF05_ZUG_SUMME_RAHM .  " ZUG_SUMME_RAHM
*
*  INCLUDE FM06BF05_ZUG_SUMME_BEST .  " ZUG_SUMME_BEST
*
*
*  INCLUDE FM06BF05_ZUG_ZEILEN .  " ZUG_ZEILEN
*
*  INCLUDE FM06BF05_ZUG_SUMME_ZNIX .  " ZUG_SUMME_ZNIX
*
*  INCLUDE FM06BF05_ZUG_SUMME_ZRES .  " ZUG_SUMME_ZRES

  INCLUDE zfm06bf05_ban_update .  " BAN_UPDATE

  INCLUDE zfm06bf05_ban_update_aendern .  " BAN_UPDATE_AENDERN

  INCLUDE zfm06bf05_bat_aufbauen .  " BAT_AUFBAUEN

  INCLUDE zfm06bf05_generieren_anfrage .  " GENERIEREN_ANFRAGE

  INCLUDE zfm06bf05_generieren_bestellun .  " GENERIEREN_BESTELLUNG

  INCLUDE zfm06bf05_generieren_erfassung .  " GENERIEREN_ERFASSUNGSBLATT

  INCLUDE zfm06bf05_generieren_einteilun .  " GENERIEREN_EINTEILUNG

  INCLUDE zfm06bf05_generieren_umlagbest .  " GENERIEREN_UMLAGBESTELLUNG

  INCLUDE zfm06bf05_zug_aendern .  " ZUG_AENDERN

  INCLUDE zfm06bf05_zug_bearbeiten .  " ZUG_BEARBEITEN

  INCLUDE zfm06bf05_zug_clear .  " ZUG_CLEAR

  INCLUDE zfm06bf05_zug_hide .  " ZUG_HIDE

  INCLUDE zfm06bf05_zug_modif_zeile .  " ZUG_MODIF_ZEILE

  INCLUDE zfm06bf05_zug_summe .  " ZUG_SUMME

  INCLUDE zfm06bf05_zug_summe_anfr .  " ZUG_SUMME_ANFR

  INCLUDE zfm06bf05_zug_summe_lief .  " ZUG_SUMME_LIEF

  INCLUDE zfm06bf05_zug_summe_ohne .  " ZUG_SUMME_OHNE

  INCLUDE zfm06bf05_zug_summe_rahm .  " ZUG_SUMME_RAHM

  INCLUDE zfm06bf05_zug_summe_best .  " ZUG_SUMME_BEST


  INCLUDE zfm06bf05_zug_zeilen .  " ZUG_ZEILEN

  INCLUDE zfm06bf05_zug_summe_znix .  " ZUG_SUMME_ZNIX

  INCLUDE zfm06bf05_zug_summe_zres .  " ZUG_SUMME_ZRES
