*eject
************************************************************************
* Unterroutinen fuer Bearbeitung Tabelle ALF                           *
************************************************************************

*  INCLUDE FM06BFAL_ALF_BLAETTERN .  " ALF_BLAETTERN
*
*  INCLUDE FM06BFAL_ALF_FIRST .  " ALF_FIRST
*
*  INCLUDE FM06BFAL_ALF_FUELLEN .  " ALF_FUELLEN
*
*  INCLUDE FM06BFAL_ALF_INIT .  " ALF_INIT
*
*  INCLUDE FM06BFAL_ALF_LESEN .  " ALF_LESEN
*
*  INCLUDE FM06BFAL_ALF_LOESCHEN .  " ALF_LOESCHEN
*
*  INCLUDE FM06BFAL_ALF_LOESCHEN_EINZEL .  " ALF_LOESCHEN_EINZEL

  INCLUDE zFM06BFAL_ALF_BLAETTERN .  " ALF_BLAETTERN

  INCLUDE zFM06BFAL_ALF_FIRST .  " ALF_FIRST

  INCLUDE zFM06BFAL_ALF_FUELLEN .  " ALF_FUELLEN

  INCLUDE zFM06BFAL_ALF_INIT .  " ALF_INIT

  INCLUDE zFM06BFAL_ALF_LESEN .  " ALF_LESEN

  INCLUDE zFM06BFAL_ALF_LOESCHEN .  " ALF_LOESCHEN

  INCLUDE zFM06BFAL_ALF_LOESCHEN_EINZEL .  " ALF_LOESCHEN_EINZEL
