"Name: \PR:SAPMM07R\FO:POPUP_VERLASSEN\SE:BEGIN\EI
ENHANCEMENT 0 ZMB21.
* Chermaine change to return back to the right initial screen
  IF NOT ANF_BILD IS INITIAL.
    LEAVE TO CURRENT TRANSACTION.
  ENDIF.
  IF T063C-CCODE = CCOD-DATU.
    ABBRECHEN = X.
  ENDIF.
  IF T063C-CCODE = CCOD-RSNL.
    RM07M-BDTER = OLD_BDTER.
    RM07M-WERKS = OLD_WERKS.
  ENDIF.
  IF T063C-CCODE = CCOD-RSST.
    CLEAR: RM07M-CAPID, RM07M-MATNR, RM07M-SMENG, RM07M-STLAL.
  ENDIF.
  FCODE_NEXT = OLD_FCODE.
  IF FCODE_NEXT NE FCODE AND XPF02 IS INITIAL.
    PERFORM FCODE_PRUEFEN.
    IF NOT FCAUSW-XSELP IS INITIAL.
      READ TABLE FUSS INDEX 1.
      IF NOT SY-SUBRC IS INITIAL.
        FCODE_NEXT = FCOD-AB.
        PERFORM FCODE_PRUEFEN.
      ENDIF.
    ENDIF.
  ENDIF.
  SET SCREEN 0.
  LEAVE SCREEN.
ENDENHANCEMENT.
