
CONSTANTS: A TYPE C VALUE 'A',
           B TYPE C VALUE 'B',
           C TYPE C VALUE 'C',
           D TYPE C VALUE 'D',
           E TYPE C VALUE 'E',
           F TYPE C VALUE 'F',
           G TYPE C VALUE 'G',
           H TYPE C VALUE 'H',
           I TYPE C VALUE 'I',
           J TYPE C VALUE 'J',
           K TYPE C VALUE 'K',
           L TYPE C VALUE 'L',
           M TYPE C VALUE 'M',
           N TYPE C VALUE 'N',
           O TYPE C VALUE 'O',
           P TYPE C VALUE 'P',
           Q TYPE C VALUE 'Q',
           R TYPE C VALUE 'R',
           S TYPE C VALUE 'S',
           T TYPE C VALUE 'T',
           U TYPE C VALUE 'U',
           V TYPE C VALUE 'V',
           W TYPE C VALUE 'W',
           X TYPE C VALUE 'X',
           Y TYPE C VALUE 'Y',
           Z TYPE C VALUE 'Z'.

CONSTANTS: PLUS  TYPE C VALUE '+',
           MINUS TYPE C VALUE '-',
           PUNKT TYPE C VALUE '.',
           NULL  TYPE C VALUE '0',
           EINS  TYPE C VALUE '1',
           ZWEI  TYPE C VALUE '2',
           DREI  TYPE C VALUE '3',
           VIER  TYPE C VALUE '4',
           FUENF TYPE C VALUE '5',
           SECHS TYPE C VALUE '6',
          SIEBEN TYPE C VALUE '7',
           ACHT  TYPE C VALUE '8',
           NEUN  TYPE C VALUE '9',
           EINSI TYPE I VALUE '1',
           ZWEII TYPE I VALUE '2',
           DREII TYPE I VALUE '3',
           VIERI TYPE I VALUE '4',
           NZWEI TYPE I VALUE '02',
           NDREI TYPE I VALUE '03'.

CONSTANTS: ACTVT01 LIKE TACT-ACTVT VALUE '01',
           ACTVT02 LIKE TACT-ACTVT VALUE '02',
           ACTVT03 LIKE TACT-ACTVT VALUE '03',
           ACTVT04 LIKE TACT-ACTVT VALUE '04',
           ACTVT06 LIKE TACT-ACTVT VALUE '06',
           ACTVT65 LIKE TACT-ACTVT VALUE '65',
           ACTVT70 LIKE TACT-ACTVT VALUE '70'.

CONSTANTS: MAXIMUM     TYPE F VALUE 9999999999999,
           MINIMUM     TYPE F VALUE -9999999999999,
           MAXIMUM_GLD TYPE F VALUE  99999999999,
           MINIMUM_GLD TYPE F VALUE  -99999999999,
           MAXVALUE LIKE AM07M-MAXVALUE VALUE 9999999999999,
           MINVALUE LIKE AM07M-MAXVALUE VALUE -9999999999999,
           CNULL(18)   TYPE C VALUE '000000000000000000',
           PF02(4)     TYPE C VALUE 'PF02',
           PF15(4)     TYPE C VALUE 'PF15',
           STERN       TYPE C VALUE '*',
           DOUBLESTAR(2) TYPE C VALUE '**',
           UNDERSCORE  TYPE C VALUE '_',
           SLASCH      TYPE C VALUE '/',
           DPUNKT      TYPE C VALUE ':',
           CURTP00     LIKE SMBEW-CURTP VALUE '00', "Transaktionswährung
           CURTP10     LIKE SMBEW-CURTP VALUE '10', "ML in Hauswährung
           AUTO_BEST   LIKE MSEG-EBELN  VALUE '9999999999',
           MODULPOOL   LIKE SY-REPID    VALUE 'SAPMM07M'.

CONSTANTS  cv_first_time TYPE i VALUE '1'.

CONSTANTS: BEGIN OF HLP,
             B(4) TYPE C VALUE 'HLPB',
             F(4) TYPE C VALUE 'HLPF',
             G(4) TYPE C VALUE 'HLPG',
             M(4) TYPE C VALUE 'HLPM',
             R(4) TYPE C VALUE 'HLPR',
             V(4) TYPE C VALUE 'HLPV',
           END OF HLP.
*eject
