*&---------------------------------------------------------------------*
*&  Include           ZMMINT_0002_TOP
*&---------------------------------------------------------------------*
TYPES: BEGIN OF ty_item,
         mark  TYPE c,
         fix   TYPE c,
         bukrs TYPE bukrs,
         ekorg TYPE ekorg,
         ekgrp TYPE ekgrp,
         lifnr TYPE lifnr,
         name1 TYPE name1_gp,
         banfn TYPE banfn,
         bnfpo TYPE bnfpo,
         matnr TYPE matnr,
         matkl TYPE matkl,
         mtart TYPE mtart,
         maktx TYPE maktx,
         werks TYPE werks_d,
         pstyp TYPE pstyp,
         knttp TYPE knttp,
         ktmng TYPE ktmng,
         menge TYPE bstmg,
         meins TYPE bstme,
         waers TYPE waers,
         netpr TYPE bwert,
         netwr TYPE bwert,
         txz01 TYPE txz01,
         hkont TYPE hkont,
         kostl TYPE kostl,
         ebeln TYPE ebeln,
*     Start Insert for TR P30K909486
         lifnr_curr         TYPE lifnr,
         price_ext          TYPE text1000,
         saving             TYPE text1000,
         item_cat_ariba(60) TYPE c,
*     End Insert for TR P30K909486
       END OF ty_item.

TYPES: BEGIN OF ty_excel,
         col01              TYPE text1000,
         col02              TYPE text1000,
         col03              TYPE text1000,
         col04              TYPE text1000,
         col05              TYPE text1000,
         col06              TYPE text1000,
         col07              TYPE text1000,
         col08              TYPE text1000,
         col09              TYPE text1000,
         col10              TYPE text1000,
         col11              TYPE text1000,
         col12              TYPE text1000,
         col13              TYPE text1000,
         col14              TYPE text1000,
         col15              TYPE text1000,
         col16              TYPE text1000,
         col17              TYPE text1000,
         col18              TYPE text1000,
         col19              TYPE text1000,
         col20              TYPE text1000,
         col21              TYPE text1000,
         col22              TYPE text1000,
         col23              TYPE text1000,
         col24              TYPE text1000,
         col25              TYPE text1000,
         col26              TYPE text1000,
         col27              TYPE text1000,
         col28              TYPE text1000,
         col29              TYPE text1000,
         col30              TYPE text1000,
         col31              TYPE text1000,
         col32              TYPE text1000,
         col33              TYPE text1000,
         col34              TYPE text1000,
         col35              TYPE text1000,
         col36              TYPE text1000,
         col37              TYPE text1000,
         col38              TYPE text1000,
         col39              TYPE text1000,
         col40              TYPE text1000,
         col41              TYPE text1000,
         col42              TYPE text1000,
         col43              TYPE text1000,
         col44              TYPE text1000,
         col45              TYPE text1000,
         col46              TYPE text1000,
         col47              TYPE text1000,
         col48              TYPE text1000,
         col49              TYPE text1000,
         col50              TYPE text1000,
         col51              TYPE text1000,
         col52              TYPE text1000,
         col53              TYPE text1000,
         col54              TYPE text1000,
         col55              TYPE text1000,
         col56              TYPE text1000,
         col57              TYPE text1000,
         col58              TYPE text1000,
         col59              TYPE text1000,
         col60              TYPE text1000,
         col61              TYPE text1000,
         col62              TYPE text1000,
         col63              TYPE text1000,
         col64              TYPE text1000,
         col65              TYPE text1000,
         col66              TYPE text1000,
         col67              TYPE text1000,
         col68              TYPE text1000,
         col69              TYPE text1000,
         col70              TYPE text1000,
         name1              TYPE name1_gp,
         matnr              TYPE matnr_d,
         statu              TYPE text1000,
         maktx              TYPE maktx,
         netpr              TYPE text1000,
         menge              TYPE text1000,
         matkl              TYPE matkl,
         mtart              TYPE mtart,
         werks              TYPE werks_d,
         meins              TYPE bstme,
         waers              TYPE waers,
         bukrs              TYPE bukrs,
         ekorg              TYPE ekorg,
         ekgrp              TYPE ekgrp,
* --> Start added by Allan Taufiq P30K908768 - 18.12.2016
         lifnr              TYPE lifnr,
* <-- End added by Allan Taufiq P30K908768 - 18.12.2016
*     Start Insert for TR P30K909486
         lifnr_curr         TYPE lifnr,
         price_ext          TYPE text1000,
         saving             TYPE text1000,
         item_cat_ariba(60) TYPE c,
*     End Insert for TR P30K909486
       END OF ty_excel.

TYPES: BEGIN OF ty_lfa1,
         lifnr TYPE lifnr,
         name1 TYPE name1_gp,
       END OF ty_lfa1.

TYPES: BEGIN OF ty_makt,
         matnr TYPE matnr_d,
         maktx TYPE maktx,
       END OF ty_makt.

TYPES: BEGIN OF ty_t161,
         bsart TYPE esart,
         batxt TYPE batxt,
       END OF ty_t161.

TYPES: ty_t_item    TYPE TABLE OF ty_item,
       ty_t_excel   TYPE TABLE OF ty_excel,
       ty_t_message TYPE TABLE OF string,
       ty_t_lfa1    TYPE TABLE OF ty_lfa1,
       ty_t_makt    TYPE TABLE OF ty_makt,
       ty_t_t161    TYPE TABLE OF ty_t161.

DATA: gt_item    TYPE ty_t_item,
      gs_item    TYPE ty_item,
      gt_data    TYPE ty_t_excel,
      gt_message TYPE ty_t_message.

DATA: p_document_id TYPE string,
      p_filename    TYPE localfile,
      p_banfn       TYPE banfn,
      p_bldat       TYPE bldat,
      p_evart       TYPE evart,
      p_werks       TYPE ewerk,
      p_bukrs       TYPE bukrs,
      p_ekorg       TYPE ekorg,
      p_ekgrp       TYPE ekgrp,
      p_vdatu       TYPE ordab,
      p_bdatu       TYPE ordbi,
      p_kostl       TYPE kostl,
      p_hkont       TYPE hkont,
      cb_contract   TYPE c,
      cb_po         TYPE c,
      cb_pir        TYPE c,
      cb_cp         TYPE c,
      okcode        TYPE sy-ucomm.

DATA: gv_ariba_sid     TYPE xuvalue,
      gv_purchaseorder TYPE bapimepoheader-po_number,
      gv_contract      TYPE bapimeoutheader-number,
      gv_infnr         TYPE infnr,
      gv_pir_valid     TYPE flag.

* --> Start changed by Allan Taufiq P30K908768 - 18.12.2016
*RANGES: gr_name1 FOR lfa1-name1.
* <-- End changed by Allan Taufiq P30K908768 - 18.12.2016

CONTROLS: tc9100 TYPE TABLEVIEW USING SCREEN 9100.
