*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMMPONUMTOP.                      " Global Data
  INCLUDE LZMMPONUMUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMMPONUMF00                            . " subprograms
  INCLUDE LZMMPONUMI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMMPONUMF...                      " Subprograms
* INCLUDE LZMMPONUMO...                      " PBO-Modules
* INCLUDE LZMMPONUMI...                      " PAI-Modules

INCLUDE LZMMPONUMF01.
