DATA: BEGIN OF UCOM,                       "#EC NEEDED
        ABBR(4) TYPE C VALUE 'ABBR',
        ALLE(4) TYPE C VALUE 'ALLE',
        ANZK(4) TYPE C VALUE 'ANZK',
        AUSL(4) TYPE C VALUE 'AUSL',
        AUSR(4) TYPE C VALUE 'AUSR',
        AUSW(4) TYPE C VALUE 'AUSW',
        AUFR(4) TYPE C VALUE 'AUFR',
        BACK(4) TYPE C VALUE 'BACK',
        BCHA(4) TYPE C VALUE 'BCHA',
        BELA(4) TYPE C VALUE 'BELA',
        BLOC(4) TYPE C VALUE 'BLOC',
        BUCH(4) TYPE C VALUE 'BU  ',
        CANC(4) TYPE C VALUE 'CANC',
        DRUK(4) TYPE C VALUE 'DRUK',
        ECAN(4) TYPE C VALUE 'ECAN',
        ENDE(4) TYPE C VALUE 'ENDE',
        EXIT(4) TYPE C VALUE 'EXIT',
        FK03(4) TYPE C VALUE 'FK03',
        GRUN(4) TYPE C VALUE 'GRUN',
        LIEF(4) TYPE C VALUE 'LIEF',
        LORT(4) TYPE C VALUE 'LORT',
        MALL(4) TYPE C VALUE 'MALL',
        MALO(4) TYPE C VALUE 'MALO',
        MAPP(4) TYPE C VALUE 'MAPP',
        MARK(4) TYPE C VALUE 'MARK',
        MATB(4) TYPE C VALUE 'MATB',
        MB51(4) TYPE C VALUE 'MB51',
        MB23(4) TYPE C VALUE 'MB23',
        MCHB(4) TYPE C VALUE 'MCHB',
        MEIN(4) TYPE C VALUE 'MEIN',
        MEIL(4) TYPE C VALUE 'MEIL',
        MINU(4) TYPE C VALUE 'MINU',
        MM03(4) TYPE C VALUE 'MM03',
        MMBE(4) TYPE C VALUE 'MMBE',
        MSK3(4) TYPE C VALUE 'MSK3',
        MI22(4) TYPE C VALUE 'MI22',
        MKOL(4) TYPE C VALUE 'MKOL',
        NANZ(4) TYPE C VALUE 'NANZ',
        NEGA(4) TYPE C VALUE 'NEGA',
        NEXT(4) TYPE C VALUE 'NEXT',
        NMAT(4) TYPE C VALUE 'NMAT',
        NOCH(4) TYPE C VALUE 'NOCH',
        PRAZ(4) TYPE C VALUE 'PRAZ',
        PREV(4) TYPE C VALUE 'PREV',
        PRIN(4) TYPE C VALUE 'PRIN',
        PRPR(4) TYPE C VALUE 'PRPR',
        SACK(4) TYPE C VALUE 'SACK',
        SUMM(4) TYPE C VALUE 'SUMM',
        SUM1(4) TYPE C VALUE 'SUM1',
        SUM2(4) TYPE C VALUE 'SUM2',
        SUMA(4) TYPE C VALUE 'SUMA',
        SPAL(4) TYPE C VALUE 'SPAL',
        SORT(4) TYPE C VALUE 'SORT',
        SPAM(4) TYPE C VALUE 'SPAM',
        SORM(4) TYPE C VALUE 'SORM',
        TEXT(4) TYPE C VALUE 'TEXT',
        VERB(4) TYPE C VALUE 'VERB',
        VERF(4) TYPE C VALUE 'VERF',
        VKPR(4) TYPE C VALUE 'VKPR',
        VMAT(4) TYPE C VALUE 'VMAT',
* &002 begin: Taste "InvBeleg übernehmen" in Mi22 eingbaut
        UEBN(4) TYPE C VALUE 'UEBN',
* &002 end
      END OF UCOM.

DATA: SE38(4) TYPE C VALUE 'SE38',
      TRX0(4) TYPE C VALUE '    '.

*eject
